### ISSUE TITLE
running alpino

### ISSUE THREAD

**Issue by piekvossen** [cltl/vu-rm-pip3#3]
Cannot find the KafNafParserPy from where where alpino is ran. It is located deep down in the module: opinion_miner_deluxePP

-- Running alpino
Traceback (most recent call last):
File "/anaconda3/lib/python3.6/runpy.py", line 183, in _run_module_as_main
mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
File "/anaconda3/lib/python3.6/runpy.py", line 142, in _get_module_details
return _get_module_details(pkg_main_name, error)
File "/anaconda3/lib/python3.6/runpy.py", line 109, in _get_module_details
__import__(pkg_name)
File "/Tools/vu-rm-pip3/components/python/morphosyntactic_parser_nl/alpinonaf/__init__.py", line 1, in <module>
from .morph_syn_parser import parse, __version__
File "/Tools/vu-rm-pip3/components/python/morphosyntactic_parser_nl/alpinonaf/morph_syn_parser.py", line 13, in <module>
from KafNafParserPy import *
ModuleNotFoundError: No module named 'KafNafParserPy'
module alpino returned an error

**Comment by sarnoult** [comment]
With the current installation script, the opinion-miner module installs KafNafParserPy locally from the repository, while the alpino wrapper expects to have it in the python environment. It's confusing and I will clean that up.

The alpino wrapper should work if KafNafParserPy is in your python environment. Have you installed the ./env/requirements.txt in it?

**Comment by piekvossen** [comment]
You are right. I overlooked that in the README.MD. I reinstalled and it now finds the parser. Thanks!
